parameters:
  env(TOKEN): ''
  env(BUCKET_NAME): ''
  env(PUBLIC_ASSETS_BASE_URL): ''
  github_token: '%env(TOKEN)%'
  bucket_name: '%env(BUCKET_NAME)%'
  module_list_repository: 'prestashop/native-modules'
  public_assets_base_url: '%env(PUBLIC_ASSETS_BASE_URL)%'
  prestashop_os_repository: 'PrestaShop/PrestaShop'
  prestashop_classic_repository: 'PrestaShopCorp/prestashop-classic'
  prestashop_os_min_version: '1.7.0.0'
  prestashop_classic_min_version: '9.0.0-0.1'
